version: 2.1

orbs:
 android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run:
          command: ./gradlew build

  test:
    executor: android/android
    steps:
      - test
      - run:
          command: ./gradlew test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
